#!/usr/bin/env python3
"""
Unit tests for GithubOrgClient.
"""

import unittest
from unittest.mock import patch, PropertyMock
from parameterized import parameterized, parameterized_class
from client import GithubOrgClient
from fixtures import org_payload, repos_payload, expected_repos, apache2_repos


class TestGithubOrgClient(unittest.TestCase):
        """Test suite for GithubOrgClient."""

            @parameterized.expand([
                        ("google", {"login": "google"}),
                                ("abc", {"login": "abc"})
                                    ])
                @patch('client.get_json')
                    def test_org(self, org_name: str, expected_payload: dict, mock_get_json: unittest.mock.Mock) -> None:
                                """Test that GithubOrgClient.org returns the correct value."""
                                        mock_get_json.return_value = expected_payload
                                                client = GithubOrgClient(org_name)
                                                        self.assertEqual(client.org, expected_payload)
                                                                mock_get_json.assert_called_once_with(f"https://api.github.com/orgs/{org_name}")

                                                                    def test_public_repos_url(self) -> None:
                                                                                """Test the _public_repos_url property."""
                                                                                        with patch('client.GithubOrgClient.org', new_callable=PropertyMock) as mock_org:
                                                                                                        mock_org.return_value = {"repos_url": "https://api.github.com/orgs/google/repos"}
                                                                                                                    client = GithubOrgClient("google")
                                                                                                                                self.assertEqual(client._public_repos_url, "https://api.github.com/orgs/google/repos")

                                                                                                                                    @patch('client.get_json')
                                                                                                                                        def test_public_repos(self, mock_get_json: unittest.mock.Mock) -> None:
                                                                                                                                                    """Test public_repos method."""
                                                                                                                                                            mock_get_json.return_value = [{"name": "repo1"}, {"name": "repo2"}]
                                                                                                                                                                    with patch('client.GithubOrgClient._public_repos_url', new_callable=PropertyMock) as mock_url:
                                                                                                                                                                                    mock_url.return_value = "https://api.github.com/orgs/google/repos"
                                                                                                                                                                                                client = GithubOrgClient("google")
                                                                                                                                                                                                            self.assertEqual(client.public_repos(), ["repo1", "repo2"])
                                                                                                                                                                                                                        mock_url.assert_called_once()
                                                                                                                                                                                                                                    mock_get_json.assert_called_once_with("https://api.github.com/orgs/google/repos")

                                                                                                                                                                                                                                        @parameterized.expand([
                                                                                                                                                                                                                                                    ({"license": {"key": "my_license"}}, "my_license", True),
                                                                                                                                                                                                                                                            ({"license": {"key": "other_license"}}, "my_license", False)
                                                                                                                                                                                                                                                                ])
                                                                                                                                                                                                                                            def test_has_license(self, repo: dict, license_key: str, expected: bool) -> None:
                                                                                                                                                                                                                                                        """Test the has_license method."""
                                                                                                                                                                                                                                                                client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                        self.assertEqual(client.has_license(repo, license_key), expected)


                                                                                                                                                                                                                                                                        @parameterized_class([
                                                                                                                                                                                                                                                                                {"org_payload": org_payload, "repos_payload": repos_payload, "expected_repos": expected_repos, "apache2_repos": apache2_repos}
                                                                                                                                                                                                                                                                                ])
                                                                                                                                                                                                                                                                        class TestIntegrationGithubOrgClient(unittest.TestCase):
                                                                                                                                                                                                                                                                                """Integration test suite for GithubOrgClient."""

                                                                                                                                                                                                                                                                                    @classmethod
                                                                                                                                                                                                                                                                                        def setUpClass(cls) -> None:
                                                                                                                                                                                                                                                                                                    """Set up class for integration tests."""
                                                                                                                                                                                                                                                                                                            cls.get_patcher = patch('requests.get')
                                                                                                                                                                                                                                                                                                                    cls.mock_get = cls.get_patcher.start()

                                                                                                                                                                                                                                                                                                                            cls.mock_get.side_effect = lambda url: cls._mocked_requests_get(url)

                                                                                                                                                                                                                                                                                                                                @classmethod
                                                                                                                                                                                                                                                                                                                                    def tearDownClass(cls) -> None:
                                                                                                                                                                                                                                                                                                                                                """Tear down class for integration tests."""
                                                                                                                                                                                                                                                                                                                                                        cls.get_patcher.stop()

                                                                                                                                                                                                                                                                                                                                                            @classmethod
                                                                                                                                                                                                                                                                                                                                                                def _mocked_requests_get(cls, url: str) -> unittest.mock.Mock:
                                                                                                                                                                                                                                                                                                                                                                            """Mock requests.get().json() with fixtures data."""
                                                                                                                                                                                                                                                                                                                                                                                    if url == "https://api.github.com/orgs/google":
                                                                                                                                                                                                                                                                                                                                                                                                    return cls.MockResponse(json.dumps(cls.org_payload), 200)
                                                                                                                                                                                                                                                                                                                                                                                                        elif url == "https://api.github.com/orgs/google/repos":
                                                                                                                                                                                                                                                                                                                                                                                                                        return cls.MockResponse(json.dumps(cls.repos_payload), 200)
                                                                                                                                                                                                                                                                                                                                                                                                                            return cls.MockResponse(None, 404)

                                                                                                                                                                                                                                                                                                                                                                                                                            class MockResponse:
                                                                                                                                                                                                                                                                                                                                                                                                                                        """Mock response class for requests."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                def __init__(self, json_data: str, status_code: int) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.json_data = json_data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.status_code = status_code

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def json(self) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Return json data."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return json.loads(self.json_data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_public_repos(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Test public_repos method in integration test."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertEqual(client.public_repos(), self.expected_repos)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_public_repos_with_license(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Test public_repos method with license filtering in integration test."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertEqual(client.public_repos("apache-2.0"), self.apache2_repos)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    unittest.main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #!/usr/bin/env python3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Unit tests for GithubOrgClient.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import unittest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from unittest.mock import patch, PropertyMock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from parameterized import parameterized, parameterized_class
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from client import GithubOrgClient
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from fixtures import org_payload, repos_payload, expected_repos, apache2_repos


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class TestGithubOrgClient(unittest.TestCase):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Test suite for GithubOrgClient."""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @parameterized.expand([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ("google", {"login": "google"}),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ("abc", {"login": "abc"})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @patch('client.get_json')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_org(self, org_name: str, expected_payload: dict, mock_get_json: unittest.mock.Mock) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Test that GithubOrgClient.org returns the correct value."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mock_get_json.return_value = expected_payload
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client = GithubOrgClient(org_name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertEqual(client.org, expected_payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mock_get_json.assert_called_once_with(f"https://api.github.com/orgs/{org_name}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_public_repos_url(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Test the _public_repos_url property."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with patch('client.GithubOrgClient.org', new_callable=PropertyMock) as mock_org:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mock_org.return_value = {"repos_url": "https://api.github.com/orgs/google/repos"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.assertEqual(client._public_repos_url, "https://api.github.com/orgs/google/repos")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @patch('client.get_json')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_public_repos(self, mock_get_json: unittest.mock.Mock) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Test public_repos method."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_get_json.return_value = [{"name": "repo1"}, {"name": "repo2"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with patch('client.GithubOrgClient._public_repos_url', new_callable=PropertyMock) as mock_url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mock_url.return_value = "https://api.github.com/orgs/google/repos"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertEqual(client.public_repos(), ["repo1", "repo2"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mock_url.assert_called_once()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mock_get_json.assert_called_once_with("https://api.github.com/orgs/google/repos")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @parameterized.expand([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ({"license": {"key": "my_license"}}, "my_license", True),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ({"license": {"key": "other_license"}}, "my_license", False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_has_license(self, repo: dict, license_key: str, expected: bool) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Test the has_license method."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertEqual(client.has_license(repo, license_key), expected)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @parameterized_class([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"org_payload": org_payload, "repos_payload": repos_payload, "expected_repos": expected_repos, "apache2_repos": apache2_repos}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class TestIntegrationGithubOrgClient(unittest.TestCase):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Integration test suite for GithubOrgClient."""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @classmethod
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def setUpClass(cls) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Set up class for integration tests."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cls.get_patcher = patch('requests.get')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cls.mock_get = cls.get_patcher.start()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cls.mock_get.side_effect = lambda url: cls._mocked_requests_get(url)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @classmethod
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def tearDownClass(cls) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Tear down class for integration tests."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cls.get_patcher.stop()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @classmethod
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def _mocked_requests_get(cls, url: str) -> unittest.mock.Mock:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Mock requests.get().json() with fixtures data."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if url == "https://api.github.com/orgs/google":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return cls.MockResponse(json.dumps(cls.org_payload), 200)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif url == "https://api.github.com/orgs/google/repos":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return cls.MockResponse(json.dumps(cls.repos_payload), 200)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return cls.MockResponse(None, 404)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class MockResponse:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Mock response class for requests."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def __init__(self, json_data: str, status_code: int) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.json_data = json_data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.status_code = status_code

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def json(self) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Return json data."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return json.loads(self.json_data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def test_public_repos(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Test public_repos method in integration test."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertEqual(client.public_repos(), self.expected_repos)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def test_public_repos_with_license(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Test public_repos method with license filtering in integration test."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client = GithubOrgClient("google")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertEqual(client.public_repos("apache-2.0"), self.apache2_repos)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        unittest.main()

